# Macro file for EsercizioG4
#
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
# 
# change the default number of workers (in multi-threading mode)
#/run/numberOfThreads 4
#
# Kind of tutorial:
# interactively with visualization, issue the commands one by one:
# Idle> gun/particle mu+
# Idle> ...etc... 
#
# Initialize kernel
/run/initialize
#
# muon 1000 MeV in direction (0.,0.,1.)
/gun/particle mu+
#/gun/energy 1000 MeV
#
/run/printProgress 5
/run/beamOn 100000
#
# verbosity
#/tracking/verbose 2
#/run/beamOn 1
